

placer: *
	./build_executable.sh
	echo "if this make failed, please ensure ./build_executable.sh has execute permission";
	echo "try running 'chmod 700 build_executable.sh', and then do 'make' again";

clean:
	rm -f placer
